### ISSUE TITLE
Need for Command Line to Be Able to Utilize New Alpha Channel Capability of FFMPEG

### ISSUE THREAD

**Issue by faithdwsn** [FFmpeg/web#8]
I have searched the web for the greater half of the day including the documentation library at [https://ffmpeg.org/ffmpeg.html#Video-Options] and [https://ffmpeg.org/ffmpeg-utils.html#Expression-Evaluation]. 

I also tried to search the online git Issue sections about how to create alpha transparency in ffmpeg when converting a file over to WebM format. 

I am aware Google now allows Alpha Transparency in Chrome Video such as shared in this article here: [https://developers.google.com/web/updates/2013/07/Alpha-transparency-in-Chrome-video]. However, when I downloaded the latest FFMPEG software and tried to search through the documentation library as it suggested I could find no help in getting a command line about creating a transparency channel. 

**Negate Alpha** 
I tried negate-alpha it did not work which seemed to be the closest thing to "taking out" alpha, but trying to place values in for that parameter did not work. I find it frustrating the documentation only states the options for the value integers but not HOW TO WRITE the command lines so that the computer will accept the code.  

**Alpha Filter**
The alpha-filter and alpha-merge seem to be related to creating greyscale and/or merging videos rather than just making ONE video to maintain or create an Alpha channel.  

I just need one simple command line and cannot seem to find it. 

Please help. 

Context: The source video was a .gif and .tif with existing transparent channels I tried to convert over to a WebM while also maintaining alpha transparency. All trials and efforts sadly would not work. Any help someone can provide on clarifying how to do this would be very much appreciated. 

Thank you, 
Faith

**Comment by TimothyGu** [comment]
Hi Faith, this is an issue tracker for the FFmpeg website specifically, not a general support forum for FFmpeg itself, and so I'll have to close this.

Generally, the FFmpeg documentation pages serve as a _reference_, rather than a place you can find one-liners that do what you want. Here are some additional resources that you may consider using:

* [The FFmpeg wiki](https://trac.ffmpeg.org/#CommunityContributedDocumentation) has some community-contributed documentation that may cover your use case.
* [Super User](https://superuser.com/questions/tagged/ffmpeg) allows you to ask questions about FFmpeg, as long as you tag the question with `ffmpeg`.
* The [ffmpeg-user](https://ffmpeg.org/mailman/listinfo/ffmpeg-user) mailing list has many experts that may be able to assist. Keep in mind the [rules and etiquette](https://www.ffmpeg.org/mailing-list-faq.html#Rules-and-Etiquette) of that forum however: people might ask for a sample of your .gif/.tif file so that they could try something locally.
* Finally, I've found this [Stack Overflow post](https://stackoverflow.com/questions/43214818/how-can-i-convert-gif-to-webm-preserving-alpha-channel) that may be applicable to your situation.

Good luck!
